name: Build LaTeX document

on: 
  push:
  pull_request:
    types:
      - closed
    branches:
      - master



jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Compile LaTeX document BasicsMatricesVectors
        uses: xu-cheng/latex-action@master
        with:
          root_file: main.tex
          working_directory: Slides/BasicsMatricesVectors/

      - name: Compile LaTeX document VectorAlgebra2D
        uses: xu-cheng/latex-action@master
        with:
          root_file: main.tex
          working_directory: Slides/VectorAlgebra2D/

      - name: Compile LaTeX document VectorAlgebra3D
        uses: xu-cheng/latex-action@master
        with:
          root_file: main.tex
          working_directory: Slides/VectorAlgebra3D/

      - name: Compile LaTeX document ExampleProblemCube
        uses: xu-cheng/latex-action@master
        with:
          root_file: main.tex
          working_directory: Slides/ExampleProblemCube/

      - name: Compile LaTeX document Derivatives
        uses: xu-cheng/latex-action@master
        with:
          root_file: main.tex
          working_directory: Slides/Derivatives/

      - name: Compile LaTeX document DifferentialEquations
        uses: xu-cheng/latex-action@master
        with:
          root_file: main.tex
          working_directory: Slides/DifferentialEquations/

      - name: Compile LaTeX document VectorODE
        uses: xu-cheng/latex-action@master
        with:
          root_file: main.tex
          working_directory: Slides/VectorODE/

      - name: Compile LaTeX document Verification
        uses: xu-cheng/latex-action@master
        with:
          root_file: main.tex
          working_directory: Slides/Verification/

      - name: Compile LaTeX document PhysicalSystems
        uses: xu-cheng/latex-action@master
        with:
          root_file: main.tex
          working_directory: Slides/PhysicalSystems/






      - name: Save BasicsMatricesVectors artifact
        uses: actions/upload-artifact@v1
        with:
          name: BasicsMatricesVectors.pdf
          path: Slides/BasicsMatricesVectors/main.pdf

      - name: Save VectorAlgebra2D artifact
        uses: actions/upload-artifact@v1
        with:
          name: VectorAlgebra2D.pdf
          path: Slides/VectorAlgebra2D/main.pdf

      - name: Save VectorAlgebra3D artifact
        uses: actions/upload-artifact@v1
        with:
          name: VectorAlgebra3D.pdf
          path: Slides/VectorAlgebra3D/main.pdf

      - name: Save ExampleProblemCube artifact
        uses: actions/upload-artifact@v1
        with:
          name: ExampleProblemCube.pdf
          path: Slides/ExampleProblemCube/main.pdf

      - name: Save Derivatives artifact
        uses: actions/upload-artifact@v1
        with:
          name: Derivatives.pdf
          path: Slides/Derivatives/main.pdf

      - name: Save DifferentialEquations artifact
        uses: actions/upload-artifact@v1
        with:
          name: DifferentialEquations.pdf
          path: Slides/DifferentialEquations/main.pdf

      - name: Save VectorODE artifact
        uses: actions/upload-artifact@v1
        with:
          name: VectorODE.pdf
          path: Slides/VectorODE/main.pdf

      - name: Save Verification artifact
        uses: actions/upload-artifact@v1
        with:
          name: Verification.pdf
          path: Slides/Verification/main.pdf

      - name: Save PhysicalSystems artifact
        uses: actions/upload-artifact@v1
        with:
          name: PhysicalSystems.pdf
          path: Slides/PhysicalSystems/main.pdf




      - name: Update compiled PDFs in git repository
        if: github.event.pull_request.merged == true || github.event_name == 'push'
        run: |
          git config --global user.name 'CI PDF compiler'
          git config --global user.email '<>'
          git add Slides/BasicsMatricesVectors/main.pdf
          git add Slides/VectorAlgebra2D/main.pdf
          git add Slides/VectorAlgebra3D/main.pdf
          git add Slides/ExampleProblemCube/main.pdf
          git add Slides/Derivatives/main.pdf
          git add Slides/DifferentialEquations/main.pdf
          git add Slides/VectorODE/main.pdf
          git add Slides/Verification/main.pdf
          git add Slides/PhysicalSystems/main.pdf



          git commit -m "Update compiled PDFs"
          git push
